[project]
site_name = "My Site"

nav = [
  { "Home" = "index.md" },
  { "Command Line & Git" = [
    { "Introduction" = "git-cli/index.md" },
  ] },
  { "Testing" = [
    "testing/index.md",
  ] },
  { "Containers" = [
    "containers/index.md",
  ] },
  { "Kubernetes" = [
    "kubernetes/index.md",
  ] },
]

[project.theme]
variant = "modern"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

